default_agent: cfn_mcp_server
agents:
  mcp_server:
    name: mcp_server
    language: python
    node_version: '20'
    entrypoint: /Users/adhavle/Documents/SDFC Industries/AWS-provisioning-mcp/cfn-mcp-server/mcp_server.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/adhavle/Documents/SDFC Industries/AWS-provisioning-mcp/cfn-mcp-server
    aws:
      execution_role: arn:aws:iam::905767016260:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-f6e3659767
      execution_role_auto_create: false
      account: '905767016260'
      region: us-east-1
      ecr_repository: 905767016260.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-mcp_server
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: mcp_server-VpWbdyCLTH
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:905767016260:runtime/mcp_server-VpWbdyCLTH
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-mcp_server-builder
      execution_role: arn:aws:iam::905767016260:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-f6e3659767
      source_bucket: bedrock-agentcore-codebuild-sources-905767016260-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: mcp_server_mem-wqe2IV95o9
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:905767016260:memory/mcp_server_mem-wqe2IV95o9
      memory_name: mcp_server_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  cfn_mcp_server:
    name: cfn_mcp_server
    language: python
    node_version: '20'
    entrypoint: /Users/adhavle/Documents/SDFC Industries/AWS-provisioning-mcp/cfn-mcp-server/mcp_server.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/adhavle/Documents/SDFC Industries/AWS-provisioning-mcp/cfn-mcp-server
    aws:
      execution_role: arn:aws:iam::611291728384:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-b4d325b89a
      execution_role_auto_create: false
      account: '611291728384'
      region: us-east-1
      ecr_repository: 611291728384.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-cfn_mcp_server
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: cfn_mcp_server-4KOBaDFd4a
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:611291728384:runtime/cfn_mcp_server-4KOBaDFd4a
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-cfn_mcp_server-builder
      execution_role: arn:aws:iam::611291728384:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-b4d325b89a
      source_bucket: bedrock-agentcore-codebuild-sources-611291728384-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: cfn_mcp_server_mem-EQ5V8VC0OO
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:611291728384:memory/cfn_mcp_server_mem-EQ5V8VC0OO
      memory_name: cfn_mcp_server_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
