default_agent: mcp_server
agents:
  mcp_server:
    name: mcp_server
    language: python
    node_version: '20'
    entrypoint: /Users/adhavle/Documents/SDFC Industries/AWS-provisioning-mcp/cfn-mcp-server/mcp_server.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/adhavle/Documents/SDFC Industries/AWS-provisioning-mcp/cfn-mcp-server
    aws:
      execution_role: arn:aws:iam::905767016260:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-f6e3659767
      execution_role_auto_create: false
      account: '905767016260'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-905767016260-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: mcp_server-CxkrO53RPH
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:905767016260:runtime/mcp_server-CxkrO53RPH
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: mcp_server_mem-wqe2IV95o9
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:905767016260:memory/mcp_server_mem-wqe2IV95o9
      memory_name: mcp_server_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
